gpu024
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:14<00:14, 14.47s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:18<00:00,  8.28s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:18<00:00,  9.21s/it]
Processing questions:   0%|          | 0/21 [00:00<?, ?it/s]/home/kchimmad_umass_edu/.conda/envs/IESLAnalyse/lib/python3.12/site-packages/transformers/generation/configuration_utils.py:590: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/kchimmad_umass_edu/.conda/envs/IESLAnalyse/lib/python3.12/site-packages/transformers/generation/configuration_utils.py:595: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Processing questions:   5%|▍         | 1/21 [00:32<10:49, 32.50s/it]Processing questions:  10%|▉         | 2/21 [01:12<11:35, 36.62s/it]Processing questions:  14%|█▍        | 3/21 [02:26<16:13, 54.08s/it]Processing questions:  19%|█▉        | 4/21 [03:02<13:13, 46.70s/it]Processing questions:  24%|██▍       | 5/21 [03:31<10:49, 40.57s/it]Processing questions:  29%|██▊       | 6/21 [04:05<09:30, 38.04s/it]Processing questions:  33%|███▎      | 7/21 [04:35<08:16, 35.46s/it]Processing questions:  38%|███▊      | 8/21 [05:37<09:30, 43.89s/it]Processing questions:  43%|████▎     | 9/21 [06:07<07:57, 39.80s/it]Processing questions:  48%|████▊     | 10/21 [06:40<06:54, 37.68s/it]Processing questions:  52%|█████▏    | 11/21 [07:09<05:50, 35.05s/it]Processing questions:  57%|█████▋    | 12/21 [07:43<05:12, 34.72s/it]Processing questions:  62%|██████▏   | 13/21 [08:58<06:13, 46.74s/it]Processing questions:  67%|██████▋   | 14/21 [10:12<06:26, 55.15s/it]Processing questions:  71%|███████▏  | 15/21 [10:49<04:57, 49.58s/it]Processing questions:  76%|███████▌  | 16/21 [11:40<04:09, 49.94s/it]Processing questions:  81%|████████  | 17/21 [12:57<03:52, 58.15s/it]Processing questions:  86%|████████▌ | 18/21 [13:35<02:35, 51.95s/it]Processing questions:  90%|█████████ | 19/21 [14:51<01:58, 59.23s/it]Processing questions:  95%|█████████▌| 20/21 [16:00<01:02, 62.35s/it]Processing questions: 100%|██████████| 21/21 [16:18<00:00, 48.98s/it]Processing questions: 100%|██████████| 21/21 [16:18<00:00, 46.61s/it]
Traceback (most recent call last):
  File "/scratch3/workspace/wenlongzhao_umass_edu-reason/dev_kedar/Bidirectional-Teacher-Student-Communication-for-LLM-Alignment/kchimmad/inference3B.py", line 117, in <module>
    score = get_score(data_eval_path,output_file_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch3/workspace/wenlongzhao_umass_edu-reason/dev_kedar/Bidirectional-Teacher-Student-Communication-for-LLM-Alignment/kchimmad/score_preds.py", line 39, in get_score
    df.loc[i,'score'] = exact_match_metric.compute(predictions = [df.iloc[i]['model_answer']], references = [test.iloc[i]['GT_Answer']])['exact_match']
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kchimmad_umass_edu/.conda/envs/IESLAnalyse/lib/python3.12/site-packages/evaluate/module.py", line 455, in compute
    self.add_batch(**inputs)
  File "/home/kchimmad_umass_edu/.conda/envs/IESLAnalyse/lib/python3.12/site-packages/evaluate/module.py", line 546, in add_batch
    raise ValueError(error_msg) from None
ValueError: Predictions and/or references don't match the expected format.
Expected format: {'predictions': Value(dtype='string', id='sequence'), 'references': Value(dtype='string', id='sequence')},
Input predictions: [None],
Input references: ['70000']
